if ( MSVC )
  include(compiler/msvc)
elseif ( MINGW )
  if(CMAKE_C_COMPILER MATCHES "clang")
    include(compiler/clang)
  elseif(CMAKE_C_COMPILER MATCHES "cc")
    include(compiler/gcc)
  endif()
  include(compiler/mingw)
endif()
